# Generated by Django 3.0.7 on 2020-06-22 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 22, 10, 30, 1, 825152, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
