# Generated by Django 3.0.7 on 2020-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_auto_20200715_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
